const currencies = [
  { label: "United States Dollar (USD)", value: "USD" },
  { label: "Euro (EUR)", value: "EUR" },
  { label: "British Pound Sterling (GBP)", value: "GBP" },
  { label: "Japanese Yen (JPY)", value: "JPY" },
  { label: "Moroccan Dirham (MAD)", value: "MAD" },
  { label: "Swiss Franc (CHF)", value: "CHF" },
  { label: "Australian Dollar (AUD)", value: "AUD" },
  { label: "Canadian Dollar (CAD)", value: "CAD" },
  { label: "Chinese Yuan (CNY)", value: "CNY" },
  { label: "Hong Kong Dollar (HKD)", value: "HKD" },
  { label: "Indian Rupee (INR)", value: "INR" },
  { label: "Indonesian Rupiah (IDR)", value: "IDR" },
  { label: "South Korean Won (KRW)", value: "KRW" },
  { label: "Mexican Peso (MXN)", value: "MXN" },
  { label: "Malaysian Ringgit (MYR)", value: "MYR" },
  { label: "New Zealand Dollar (NZD)", value: "NZD" },
  { label: "Philippine Peso (PHP)", value: "PHP" },
  { label: "Singapore Dollar (SGD)", value: "SGD" },
  { label: "Thai Baht (THB)", value: "THB" },
  { label: "South African Rand (ZAR)", value: "ZAR" },
  { label: "Brazilian Real (BRL)", value: "BRL" },
  { label: "Russian Ruble (RUB)", value: "RUB" },
  { label: "Turkish Lira (TRY)", value: "TRY" },
  { label: "Pakistani Rupee (PKR)", value: "PKR" },
  { label: "Egyptian Pound (EGP)", value: "EGP" },
  { label: "Saudi Riyal (SAR)", value: "SAR" },
  { label: "United Arab Emirates Dirham (AED)", value: "AED" },
  { label: "Colombian Peso (COP)", value: "COP" },
  { label: "Chilean Peso (CLP)", value: "CLP" },
  { label: "Argentine Peso (ARS)", value: "ARS" },
  { label: "Peruvian Nuevo Sol (PEN)", value: "PEN" },
  { label: "Venezuelan Bolívar Soberano (VES)", value: "VES" },
  { label: "Danish Krone (DKK)", value: "DKK" },
  { label: "Swedish Krona (SEK)", value: "SEK" },
  { label: "Norwegian Krone (NOK)", value: "NOK" },
  { label: "Polish Zloty (PLN)", value: "PLN" },
  { label: "Czech Koruna (CZK)", value: "CZK" },
  { label: "Hungarian Forint (HUF)", value: "HUF" },
  { label: "Palestine (Israeli) Shekel (ILS)", value: "ILS" },
  { label: "Qatari Riyal (QAR)", value: "QAR" },
  { label: "Central African CFA Franc (XAF)", value: "XAF" },
  { label: "West African CFA Franc (XOF)", value: "XOF" },
  { label: "Ghanaian Cedi (GHS)", value: "GHS" },
  { label: "Nigerian Naira (NGN)", value: "NGN" },
  { label: "Ugandan Shilling (UGX)", value: "UGX" },
  { label: "Tanzanian Shilling (TZS)", value: "TZS" },
  { label: "Rwandan Franc (RWF)", value: "RWF" },
  { label: "Zambian Kwacha (ZMW)", value: "ZMW" },
  { label: "Gambian Dalasi (GMD)", value: "GMD" },
  { label: "Mauritian Rupee (MUR)", value: "MUR" },
  { label: "Lesotho Loti (LSL)", value: "LSL" },
  { label: "Malawian Kwacha (MWK)", value: "MWK" },
  { label: "Algerian Dinar (DZD)", value: "DZD" },
  { label: "Bahraini Dinar (BHD)", value: "BHD" },
  { label: "Iraqi Dinar (IQD)", value: "IQD" },
  { label: "Jordanian Dinar (JOD)", value: "JOD" },
  { label: "Kuwaiti Dinar (KWD)", value: "KWD" },
  { label: "Lebanese Pound (LBP)", value: "LBP" },
  { label: "Libyan Dinar (LYD)", value: "LYD" },
  { label: "Omani Rial (OMR)", value: "OMR" },
  { label: "Syrian Pound (SYP)", value: "SYP" },
  { label: "Tunisian Dinar (TND)", value: "TND" },
  { label: "Yemeni Rial (YER)", value: "YER" },
];
currencies.sort(function (a, b) {
  if (a.label < b.label) {
    return -1;
  }
  if (a.value > b.value) {
    return 1;
  }
  return 0;
});

export default currencies;